REAL WORK_H , WAGE_RATE, SALARY, NET
PRINT*, "INPUT WORK_HOUR AND WORK_RATE : "
READ *, WORK_H, WAGE_RATE
SALARY=WORK_H*WAGE_RATE
IF (SALARY .GT. 1000) THEN
NET=SALARY-(.2*SALARY)
ELSE 
NET =SALARY -(.1*SALARY)
ENDIF
PRINT*, "THE GORSS SALARY : ", SALARY
PRINT*, "THE NET SALARY : ", NET
STOP
END 