REAL NUM,PREV_NUM
INTEGER I ,COUNT
PREV_NUM=0
COUNT=0
DO 10 I=1,10000000
  PRINT*, "Enter the number : "
  READ*, NUM
  IF (NUM .LT. 0) THEN
  PRINT*, COUNT
  GO TO 99
  ELSE
      IF (PREV_NUM .LT. NUM) THEN
      PRINT*, "YES"
      COUNT=COUNT+1
      PREV_NUM=NUM
      ENDIF
  ENDIF
10 CONTINUE
99 STOP 
END 