CHARACTER(LEN=50) :: NAME, QUALITY, OPINION, SUBJECT, ACTION
PRINT*, "Enter the recipient name : "
READ'(A)', NAME
PRINT*, "Choose an Opinion (EXCELLENT, SUPERIOR, GOOD) : "
READ'(A)', QUALITY
PRINT*, "Choose an opinion (WE FEEL, HOWEVER) : "
READ '(A)', OPINION
PRINT* ,"Choose subject (TO BE TIMELY AND APPROPRIATE, DOES NOT SUIT OUR CURRENT NEEDS) : "
READ '(A)', SUBJECT
PRINT*, "Choose action (SENDING YOU A CONTRACT, RETURNING IT SOON) : "
READ '(A)', ACTION
PRINT*,""
PRINT*,"DEAR ", TRIM(NAME)
PRINT*,""
PRINT*,"THE MANUSCRIPT YOU SENT US IS OF ",QUALITY//" QUALITY AND WE APPRECIATE."
PRINT*,"THE OPPORTUNITY OF REVIEWING IT. ",OPINION," THE SUBJECT MATTER ",SUBJECT,"."
PRINT*,"WE WILL BE ",ACTION," UNDER SEPARATE COVER."
PRINT*,""
PRINT*,"THANK YOU FOR YOUR INTEREST"
PRINT*,"CREATIVE PUBLISHERS"
STOP 
END