# Generated by Django 6.0.1 on 2026-02-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Bookmarks'},
        ),
    ]
