# Generated by Django 6.0.1 on 2026-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_rename_blog_body_memory_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='body',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='memory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
